# Generated by Django 5.2.6 on 2025-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('jaket', 'Jaket'), ('sepatu', 'Sepatu Bola'), ('kaus_kaki', 'Kaus Kaki'), ('aksesoris', 'Aksesoris'), ('celana', 'Celana')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
